CREATE TABLE Film (
    id INTEGER AUTO_INCREMENT NOT NULL,
    filmnavn VARCHAR(255) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE Bilett (
    id INTEGER AUTO_INCREMENT NOT NULL,
    filmnavn VARCHAR(255) NOT NULL,
    antall INTEGER NOT NULL,
    etternavn VARCHAR(255) NOT NULL,
    fornavn VARCHAR(255) NOT NULL,
    tlf VARCHAR(255) NOT NULL,
    epost VARCHAR(255) NOT NULL,
    PRIMARY KEY (id)
);
